name: PUBLISH

on:
  pull_request:
    branches:
      - develop

jobs:
  cd-auth-dot-net:
    uses: vyracare/vyracare-infra-pipes-dot-net/.github/workflows/cd-auth-dot-net.yml@main
    with:
      branch-name: ${{ github.head_ref }}
    secrets: inherit

  cd-terraform:
    needs: cd-auth-dot-net
    uses: vyracare/vyracare-infra/.github/workflows/cd-terraform.yml@main
    with:
      branch-name: ${{ github.head_ref }}
    secrets: inherit
