name: PUBLISH

on:
  pull_request:
    branches:
      - develop

jobs:
  cd-auth-dot-net:
    uses: vyracare/vyracare-infra-pipes-dot-net/.github/workflows/cd-auth-dot-net.yml@main
    with:
      branch-name: ${{ github.head_ref }}
      lambda-source-dir: Vyracare.Auth
    secrets: inherit
