name: PUBLISH

on:
  push:
    branches:
      - develop

jobs:
  cd-auth-dot-net:
    uses: vyracare/vyracare-infra-pipes-dot-net/.github/workflows/cd-auth-dot-net.yml@main
    with:
      branch-name: ${{ github.head_ref }}
    secrets: inherit

  open-pr-main:
    runs-on: ubuntu-latest
    needs: cd-auth-dot-net
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Open Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: ${{ github.ref_name }}
          destination_branch: main
          pr_title: "PR automatic ${{ github.ref_name }} into main"
          pr_body: |
            PR autom√°tica criada pelo pipeline.
            Branch de origem: `${{ github.ref_name }}`

            name: Publish Backend