name: PUBLISH

on:
  push:
    branches:
      - develop

jobs:
  cd-auth-dot-net:
    uses: vyracare/vyracare-infra-pipes-dot-net/.github/workflows/cd-auth-dot-net.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      backend-repo: ${{ github.repository }}
      project-path: Vyracare.Auth.csproj
      output-dir: backend-publish
    secrets: inherit

  open-pr-main:
    name: Open Pull Request to main
    runs-on: ubuntu-latest
    needs: cd-auth-dot-net
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Open Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: develop
          destination_branch: main
          pr_title: "ðŸš€ Merge develop into main (Auto PR via Pipeline)"
          pr_body: |
            PR automÃ¡tica criada pelo workflow **PUBLISH**.
            Branch de origem: `develop`
            Destino: `main`

            âœ… CD executado com sucesso no repositÃ³rio de infra.
            ðŸ§© Iniciado por: ${{ github.actor }}
